FROM nginx:1.28-alpine3.21

COPY nginx/nginx.conf /etc/nginx/nginx.conf

# Copy blue for default running blue
COPY nginx/blue.conf /etc/nginx/conf.d/default.conf

# COPY nginx/green.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]